export enum AdditionalHoursReason {
  ENGLISH_FIRST_YEAR = 'ENGLISH_FIRST_YEAR',
  ENGLISH = 'ENGLISH',
  ELEARNING_FIRST_YEAR = 'ELEARNING_FIRST_YEAR',
  ELEARNING = 'ELEARNING',
  EXAM_NONE = 'EXAM_NONE',
  EXAM_ORAL = 'EXAM_ORAL',
  EXAM_WRITTEN = 'EXAM_WRITTEN',
  BACHELOR_THESIS = 'BACHELOR_THESIS',
  MASTER_THESIS = 'MASTER_THESIS',
  PREDOCTORAL_PATRON = 'PREDOCTORAL_PATRON',
  DOCTORAL_PATRON = 'DOCTORAL_PATRON',
  INDIVIDUAL_STUDY_PATRON = 'INDIVIDUAL_STUDY_PATRON',
  FOREIGN_STUDY_PATRON = 'FOREIGN_STUDY_PATRON'
}
