export enum Degree {
  PROFESOR = 'PROFESOR',
  DOKTOR_HABILITOWANY = 'DOKTOR_HABILITOWANY',
  DOKTOR = 'DOKTOR',
  MAGISTER = 'MAGISTER',
  DOKTORANT = 'DOKTORANT',
  DOKTORANT_ZE_STYPENDIUM = 'DOKTORANT_ZE_STYPENDIUM',
  DOKTORANT_WDROZENIOWY = 'DOKTORANT_WDROZENIOWY',
  EKSPERT_DOKTOR = 'EKSPERT_DOKTOR',
  EKSPERT_DOKTOR_HABILITOWANY = 'EKSPERT_DOKTOR_HABILITOWANY',
  EKSPERT_PROFESOR = 'EKSPERT_PROFESOR',
  MAGISTER_INZYNIER = 'MAGISTER_INZYNIER',
  DOKTOR_INZYNIER = 'DOKTOR_INZYNIER',
  DOKTOR_HABILITOWANY_INZYNIER = 'DOKTOR_HABILITOWANY_INZYNIER',
  PROFESOR_DOKTOR_HABILITOWANY_INZYNIER = 'PROFESOR_DOKTOR_HABILITOWANY_INZYNIER'

}
