export enum Position {
  PROFESOR = 'PROFESOR',
  DOKTOR_HABILITOWANY = 'DOKTOR_HABILITOWANY',
  ADIUNKT = 'ADIUNKT',
  STARSZY_WYKLADOWCA = 'STARSZY_WYKLADOWCA',
  ASYSTENT = 'ASYSTENT',
  WYKLADOWCA = 'WYKLADOWCA',
  DOKTORANT = 'DOKTORANT',
  DOKTORANT_ZE_STYPENDIUM = 'DOKTORANT_ZE_STYPENDIUM',
  DOKTORANT_WDROZENIOWY = 'DOKTORANT_WDROZENIOWY',
  EKSPERT_DOKTOR = 'EKSPERT_DOKTOR',
  EKSPERT_DOKTOR_HABILITOWANY = 'EKSPERT_DOKTOR_HABILITOWANY',
  EKSPERT_PROFESOR = 'EKSPERT_PROFESOR',
  PROFESOR_ZWYCZAJNY = 'PROFESOR_ZWYCZAJNY',
  PROFESOR_NADZWYCZAJNY = 'PROFESOR_NADZWYCZAJNY',
  PROFESOR_ZAGRANCZNY = 'PROFESOR_ZAGRANCZNY'
}
